### ISSUE TITLE
Rule: no-mocha-only

### ISSUE THREAD

**Issue by aduth** [Automattic/eslint-plugin-wpcalypso#2]
`no-mocha-only` would mark a linting error whenever `it.only`, `describe.only`, or `context.only` are used in a test. These are typically used (and are fine to use) for debugging, and can be overlooked when committing, causing the test suite to produce incomplete results.

https://mochajs.org/#exclusive-tests

**Open questions:**
- Are there legitimate, non-debug uses for `only` for which this rule would become a nuisance?

**Comment by blowery** [comment]
> Are there legitimate, non-debug uses for only for which this rule would become a nuisance?

no.

**Comment by aduth** [comment]
Closing this. If we want it, we should pull in [`eslint-plugin-mocha`](https://www.npmjs.com/package/eslint-plugin-mocha) and use their [`mocha/no-exclusive-tests`](https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-exclusive-tests.md) rule.
