### ISSUE TITLE
Missing 2.0.0 tag and release

### ISSUE THREAD

**Issue by ntwb** [Automattic/eslint-plugin-wpcalypso#30]
With the 2.0.0 release there's currently no 2.0.0 tag or release:
• https://github.com/Automattic/eslint-plugin-wpcalypso/releases 
• https://github.com/Automattic/eslint-plugin-wpcalypso/tags

**Comment by aduth** [comment]
Thanks for the heads-up. Pushed a new v2.0.0 tag at 2eacc85 (npm release commit).
