### ISSUE TITLE
Version`3.4.0` is missing from "tags" and "releases"

### ISSUE THREAD

**Issue by ntwb** [Automattic/eslint-plugin-wpcalypso#40]
I expected to find a `v3.4.0` tag and release at the following pages, alas they are not there:

• https://github.com/Automattic/eslint-plugin-wpcalypso/releases
• https://github.com/Automattic/eslint-plugin-wpcalypso/tags

p.s. The `v3.4.0` package is correct at https://www.npmjs.com/package/eslint-plugin-wpcalypso

**Comment by aduth** [comment]
Added tag. Thanks.
