### ISSUE TITLE
Lint warning on plain template literal

### ISSUE THREAD

**Issue by dmsnell** [Automattic/eslint-plugin-wpcalypso#5]
Admittedly, template literals can be very complicated and interpolate variables inside of them. Nonetheless, the linting inside of Calypso flagged a warning for the following call…

``` js
this.translate( `Visit your site's wp-admin for all your import and export needs.` )
```

It's fine to ignore the warning, and it might require a bit of work to properly lint these guys to make sure they aren't inserting variables, but it would be nice to fix.

**Comment by deBhal** [comment]
Resolved by #6
